[variaveis]
organizationname = "Centro de respostas a incidentes"
organizationdescription = "Breve descritivo da instituicao"
signature = "Centro de respostas a incidentes"
[mail]
sender = "registrobr@domain.com.br"
national_csirt = "cert@cert.br"
[smtpauth]
host = "10.2.1.11"
user = "test"
passwd = "password"
