[variaveis]
organizationname = "Secretaria de Estado da Tributacao do Rio Grande do Norte"
organizationdescription = "Breve descritivo da instituicao"
signature = "Secretaria de Estado da Tributacao do Rio Grande do Norte"
[mail]
national_csirt = "cert@cert.br"
sender = "registrobr@set.rn.gov.br"
[smtpauth]
host = "10.2.1.11"
user = "test"
passwd = "password"

